import crypto from "crypto";

/**
 * Compatible with Werkzeug's generate_password_hash / check_password_hash.
 *
 * IMPORTANT: Werkzeug changed its DEFAULT method from `pbkdf2:sha256` to
 * `scrypt` starting in Werkzeug 2.3 (the Flask app's requirements.txt
 * pinned Werkzeug==3.0.3, which uses the scrypt default). So hashes
 * actually stored in the Google Sheet look like:
 *
 *   scrypt:32768:8:1$<salt>$<hex digest>
 *
 * not pbkdf2:sha256:... This module supports BOTH formats — scrypt for
 * compatibility with the existing sheet data, and pbkdf2 as a fallback in
 * case any older hashes exist. New hashes generated by this app use
 * scrypt, matching current Werkzeug behavior.
 */

const SALT_CHARS =
  "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";

// Werkzeug's scrypt defaults: N=2**15, r=8, p=1, derived key length 64 bytes.
const SCRYPT_N = 32768;
const SCRYPT_R = 8;
const SCRYPT_P = 1;
const SCRYPT_KEYLEN = 64;

function randomSalt(length = 16): string {
  let out = "";
  const bytes = crypto.randomBytes(length);
  for (let i = 0; i < length; i++) {
    out += SALT_CHARS[bytes[i] % SALT_CHARS.length];
  }
  return out;
}

function scryptHash(
  password: string,
  salt: string,
  N: number,
  r: number,
  p: number,
  keylen: number
): Buffer {
  // Node requires maxmem >= roughly 128 * N * r bytes; give it plenty of
  // headroom above what Werkzeug's defaults need.
  const maxmem = Math.max(128 * N * r * (p + 1), 64 * 1024 * 1024);
  return crypto.scryptSync(password, salt, keylen, { N, r, p, maxmem });
}

export function generatePasswordHash(password: string): string {
  const salt = randomSalt();
  const digest = scryptHash(
    password,
    salt,
    SCRYPT_N,
    SCRYPT_R,
    SCRYPT_P,
    SCRYPT_KEYLEN
  ).toString("hex");
  return `scrypt:${SCRYPT_N}:${SCRYPT_R}:${SCRYPT_P}$${salt}$${digest}`;
}

export function checkPasswordHash(hash: string, password: string): boolean {
  try {
    const [method, salt, hexdigest] = hash.split("$");
    if (!method || !salt || !hexdigest) return false;

    const methodParts = method.split(":");
    const algo = methodParts[0];

    let computed: Buffer;

    if (algo === "scrypt") {
      const N = parseInt(methodParts[1] || `${SCRYPT_N}`, 10);
      const r = parseInt(methodParts[2] || `${SCRYPT_R}`, 10);
      const p = parseInt(methodParts[3] || `${SCRYPT_P}`, 10);
      const keylen = hexdigest.length / 2;
      computed = scryptHash(password, salt, N, r, p, keylen);
    } else if (algo === "pbkdf2") {
      // Legacy format: pbkdf2:sha256:<iterations>$<salt>$<hexdigest>
      const hashAlgo = methodParts[1] || "sha256";
      const iterations = parseInt(methodParts[2] || "600000", 10);
      const keylen = hexdigest.length / 2;
      computed = crypto.pbkdf2Sync(password, salt, iterations, keylen, hashAlgo);
    } else {
      return false;
    }

    const a = computed;
    const b = Buffer.from(hexdigest, "hex");
    if (a.length !== b.length) return false;
    return crypto.timingSafeEqual(a, b);
  } catch {
    return false;
  }
}
